MyeShop/MyeShop.WebUI/Controllers/BasketController.cs
using MyeShop.Core.Contracts;
using MyeShop.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyeShop.WebUI.Controllers
{
	public class BasketController : Controller
	{
        IRepository<Customer> Customers;
        IBasketService BasketService;
        IOrderService OrderService;

		public BasketController(IBasketService basketService, IOrderService orderService, IRepository<Customer> customers)
		{
			this.OrderService = orderService;
            this.BasketService = basketService;
            this.Customers = customers;
		}

		// GET: Basket
		public ActionResult Index()
        {
            var viewModel = BasketService.GetBasketItems(this.HttpContext);

            return View(viewModel);
        }

        public ActionResult AddToBasket(string id)
		{
            BasketService.AddToBasket(this.HttpContext, id);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string id)
        {
            BasketService.RemoveFromBasket(this.HttpContext, id);
            return RedirectToAction("Index");
        }

        public ActionResult BasketSummary()
		{
            var viewModel = BasketService.GetBasketSummay(this.HttpContext);

            return PartialView(viewModel);
		}

        [Authorize]
        public ActionResult Checkout()
        {
            Customer customer = Customers.Collection().FirstOrDefault(c => c.Email == User.Identity.Name);
            if (customer != null)
			{
                Order order = new Order()
                {
                    Email = customer.Email,
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    State = customer.State,
                    City = customer.City,
                    Street = customer.Street,
                    ZipCode = customer.ZipCode
                };
                return View(order);
            }
            else
			{
                return RedirectToAction("Error");
			}
            
		}

        [Authorize]
        [HttpPost]
        public ActionResult Checkout(Order order)
		{
            var basketItems = BasketService.GetBasketItems(this.HttpContext);
            order.OrderStatus = "Order Created";
            order.Email = User.Identity.Name;

            // Process Payment 

            order.OrderStatus = "Payment Processed";
            OrderService.CreateOrder(order, basketItems);
            BasketService.ClearBasket(this.HttpContext);

            return RedirectToAction("ThankYou", new { OrderId = order.Id });
		}

        public ActionResult ThankYou(string OrderId)
		{
            ViewBag.OrderId = OrderId;

            return View();
		}
    }
}

MyeShop/MyeShop.WebUI/Controllers/HomeController.cs
using MyeShop.Core.Contracts;
using MyeShop.Core.Models;
using MyeShop.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyeShop.WebUI.Controllers
{
	public class HomeController : Controller
	{
		public IRepository<Product> Context;
		public IRepository<ProductCategory> productCategories;

		public HomeController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoryContext)
		{
			this.Context = productContext;
			this.productCategories = productCategoryContext;
		}

		public ActionResult Index(string category = null)
		{
			List<Product> products;
			List<ProductCategory> categories = this.productCategories.Collection().ToList();

			if (category == null)
			{
				products = Context.Collection().ToList();
			}
			else
			{
				products = Context.Collection().Where(p => p.Category == category).ToList();
			}

			ProductListViewModel plViewModel = new ProductListViewModel();
			plViewModel.Products = products;
			plViewModel.ProductCategories = categories;

			return View(plViewModel);
		}

		public ActionResult Details(string id)
		{
			Product product = Context.Find(id);
			if (product != null)
			{
				return View(product);
			}
			else
			{
				return HttpNotFound();
			}
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

MyeShop/MyeShop.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyeShop/MyeShop.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyeShop/MyeShop.WebUI/Views/Home/Details.cshtml
@model MyeShop.Core.Models.Product

@{
    ViewBag.Title = Model.Name + " Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>
    
<div>
	<div class="col-md-4">
		<img class="img-responsive" src="~/Content/ProductImages/@Model.Image" />
	</div>
	<div class="col-md-8">
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Description)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Description)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Price)
			</dt>

			<dd>
				$@Html.DisplayFor(model => model.Price)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Category)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Category)
			</dd>

			<dt></dt>
			<dd>
				<a href="@Url.Action("AddToBasket", "Basket", new { id=Model.Id })" class="btn btn-default">Add to Basket</a>
			</dd>

			<dt></dt>
			<dd>
				@Html.ActionLink("Back to List", "Index")
			</dd>
		</dl>
	</div>
</div>

<div class="col-md-12 clearfix"></div>

MyeShop/MyeShop.WebUI/Views/Home/Index.cshtml
@model MyeShop.Core.ViewModels.ProductListViewModel
@{
    ViewBag.Title = "Home Page";
}

<h1>Products</h1>

<div class="col-md-2">
	<h4>Filter by category</h4>
	<div class="list-group">
		@Html.ActionLink("All", "Index", null, new { @class = Request["Category"] == null ? "list-group-item active" : "list-group-item" })
		@foreach (var cat in Model.ProductCategories)
		{
			@Html.ActionLink(cat.Category, "Index", new { category = cat.Category }, new { @class = Request["Category"] == cat.Category ? "list-group-item active" : "list-group-item" })
		}
	</div>
</div>

<div class="col-md-10">
	@foreach (var item in Model.Products)
	{
		<div class="col-md-4 home-main">
			<div class="col-md-12">
				<img class="img" src="~/Content/ProductImages/@item.Image" />
			</div>
			<div class="col-md-12">
				<strong>
					@Html.ActionLink(item.Name, "Details", new { id = item.Id })
				</strong>
			</div>
			<div class="col-md-12">
				<p>@item.Description</p>
			</div>
			<div class="col-md-12">
				<h4>$@item.Price</h4>
			</div>
			<div class="col-md-12">
				<a href="@Url.Action("AddToBasket", "Basket", new { id=item.Id })" class="btn btn-default">Add to Basket</a>
			</div>
		</div>
	}
</div>

<div class="col-md-12 clearfix"></div>